In [ ]:
# Task 1
# Create a 1D array of numbers from 0 to 9
import numpy as np
arr= np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

In [ ]:
# TASK 2
# Create a 3×3 NumPy array of all Boolean value Trues
arr = np.reshape(np.arange(9), (3, 3))
print(arr)

In [10]:
# TASK 3
# Extract all odd numbers from array of 1-10

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7,  8, 9])
arr_odd = (arr % 2 == 1)

print(arr_odd)


[False  True False  True False  True False  True False  True]


In [ ]:
# TASK 4
# Replace all odd numbers in an array of 1-10 with -1
# I create 1D numpy array from a list
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[arr % 2 == 1] = -1
print(arr)


In [27]:
# TASK 5
# Convert a 1D array to a 2D array with 2 rows
# I create 1D numpy array from a list
# I create 1D numpy array from a list
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = arr.reshape(2, 5)
print(arr_2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [33]:
# TASK 6
# Create two arrays a and b, stack theses two arrays vertically use the np.dot and np.sum to calculate
a = np.arange(3, 12).reshape(3,3)
b = np.arange(6, 15).reshape(3,3)
c = np.dot(a, b)
print (sum)


<built-in function sum>


In [36]:
# Extention 1
# Create the followings pattern without hardcoding. use oonly NumPy function #>array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]) 
pattern_1 =[1, 1, 1]
pattern_2 =[2, 2, 2]
pattern_3 =[3, 3, 3]
pattern_123 =[1, 2, 3]
pattern_123_1 =[1, 2, 3]
pattern_123_2 =[1, 2, 3]

print (pattern_1 + pattern_2 + pattern_3 + pattern_123 + pattern_123_1 +pattern_123_2)

[1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [42]:
# Extention 2
# In two array a (1,2,3,4,5) and b(4,5,6,7,8,9)- remove all repeating ites present in array b
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
c= np.setdiff1d(a,b)
print(c)


[1 2 3]


In [50]:
# Extention 2
# Get all items between 3 and 7 from a and b sum them together
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])

print(a[3:7])
print(b[3:7])
print(sum)

[4 5]
[7 8 9]
<built-in function sum>
